# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'alamofireSimple' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire','~> 5.2'
  # Pods for alamofireSimple

  target 'alamofireSimpleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'alamofireSimpleUITests' do
    # Pods for testing
  end

end
